### ISSUE TITLE
Adding webpack.config.js breaks smart knobs

### ISSUE THREAD

**Issue by bradfrost** [storybookjs/addon-smart-knobs#33]
Hi there,
I'm a big fan of smart knobs and dynamically building knobs based on PropTypes. 

My issue is that adding a custom `webpack.config.js` to the `.storybook` directory results in the smart knobs not appearing. 

Without custom webpack config file:

<img width="538" alt="screen shot 2018-11-20 at 5 30 00 pm" src="https://user-images.githubusercontent.com/383701/48807158-afc18d80-ecea-11e8-81f7-f583446aee2b.png">

And with custom webpack config file:

<img width="539" alt="screenshot 2018-11-20 17 31 29" src="https://user-images.githubusercontent.com/383701/48807178-bc45e600-ecea-11e8-96d1-c555d5974e87.png">

Here is the content of the `webpack.config.js` file, which I'm using to [get SVG imports to play nicely with Storybook](https://github.com/storybooks/storybook/issues/4298):

```
const path = require("path");
const fs = require("fs");
const appDirectory = fs.realpathSync(process.cwd());

module.exports = (baseConfig, env, defaultConfig) => {
  // Extend defaultConfig as you need.
  defaultConfig.module.rules.push({
	test: /\.(js|jsx)$/,
	include: path.resolve(appDirectory, "src"),
	loader: require.resolve("babel-loader"),
	options: {
		presets: [require.resolve("babel-preset-react-app")],
		plugins: [
			[
				require.resolve("babel-plugin-named-asset-import"),
				{
					loaderMap: {
						svg: {
							ReactComponent:
							"@svgr/webpack?-prettier,-svgo![path]"
							}
						}
					}
				]
			]
		}
	});

	return defaultConfig;
};
```

Any idea why the introduction of this config file would cause smart knobs to fail? Thanks very much!

**Comment by montogeek** [comment]
Can you try using `defaultConfig.module.rules.unshift` instead of `push`?

**Comment by transitive-bullshit** [comment]
With this webpack config, I believe you'll now be running the babel loader over your source files once and then a second time over the previously transpiled version.

This may work for some cases, but it's fundamentally not what you want and definitely incompatible with react-docgen which smart knobs uses under the hood.

If your only use case for modifying the default storybook webpack config is to add functionality to its babel loader, then I'd recommend manipulating the existing rule `defaultConfig.module.rules.find((rule) => /babel-loader/.test(rule.loader))` instead of adding another babel rule to the config.

**Comment by bradfrost** [comment]
Thanks a bunch @transitive-bullshit! 

> If your only use case for modifying the default storybook webpack config is to add functionality to its babel loader, then I'd recommend manipulating the existing rule defaultConfig.module.rules.find((rule) => /babel-loader/.test(rule.loader)) instead of adding another babel rule to the config.

I'm pretty green with Webpack so I'm not quite sure what that means. Do you mean wiping out what I have with `defaultConfig.module.rules.find((rule) => /babel-loader/.test(rule.loader))`, or something else? Sorry for not understanding.

**Comment by igor-dv** [comment]
You can try putting a custom `.babelrc` with all these things into the .storybook dir instead of overriding the js rules.

**Comment by ndelangen** [comment]
Hey Brad, thanks for joining in and reporting this bug.

We're improving the CRA compatibility right now. I'm sorry if this caused a lot of inconvenience for you.

To assist with you current issue:

I think you need to change your webpack config to:

```js
const path = require("path");
const fs = require("fs");
const appDirectory = fs.realpathSync(process.cwd());

module.exports = (baseConfig, env, defaultConfig) => {
  // Extend defaultConfig as you need.
  const babelRule = defaultConfig.module.rules.find(r => r.loader && r.loader.match(/babel-loader/));
  
  if (babelRule) {
    babelRule.options = {
      ...babelRule.options,
      presets: [...babelRule.options.presets, require.resolve("babel-preset-react-app")]
      plugins: [
        [
          ...babelRule.options.plugins,
          require.resolve("babel-plugin-named-asset-import"),
          {
            loaderMap: {
              svg: {
                ReactComponent:
                "@svgr/webpack?-prettier,-svgo![path]"
              }
            }
          }
        ]
      ]
    }
  }

	return defaultConfig;
};
```

We'll work on fixing the CRA incompatibility asap you you don't need this config at all.

**Comment by ndelangen** [comment]
What's happening is:

Storybook has configured a loader for js-files by default.
Your config is adding an additional one.

These 2 together make it so smart knobs isn't being provided with the correct data anymore.

What I did in my code example, was to find the config storybook has added, and modify that so it has the svg config you need.

This way there's only 1 loader for js files, and it should work.

Hope this helps to explain what's going on.

**Comment by shilman** [comment]
@bradfrost To add to what @ndelangen said: it looks like you are trying the workaround for https://github.com/storybooks/storybook/issues/4298. We're trying to get a fix ready for that pronto, so hopefully you won't need the workaround and won't need to mess with webpack config. Sorry for the hassle!

**Comment by shilman** [comment]
@bradfrost FYI we've released a fix to the inline SVG issue in https://github.com/storybooks/storybook/releases/tag/v4.1.0-alpha.8

**Comment by bradfrost** [comment]
Thanks so much @shilman!

**Comment by bradfrost** [comment]
Thanks again for the help everyone. I'm still unable to get the smart knobs to work properly, but will open another issue as the custom webpack config isn't relevant anymore.
